name: Create Release Draft

on:
  push:
    tags:
      - 'v*'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Create Release Draft
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        files: |
          .next/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}